// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFLunusVh1U6JHJEZ5rP8kte974YeHtGY',
    appId: '1:838810558965:web:a6148747415e62a9bb80bc',
    messagingSenderId: '838810558965',
    projectId: 'butt3r-pokedex',
    authDomain: 'butt3r-pokedex.firebaseapp.com',
    storageBucket: 'butt3r-pokedex.appspot.com',
    measurementId: 'G-E2DSE4X9PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWjAgWBWA7ST0DH7skVNItJmjaDVmDZeI',
    appId: '1:838810558965:android:45f9edc123f132fcbb80bc',
    messagingSenderId: '838810558965',
    projectId: 'butt3r-pokedex',
    storageBucket: 'butt3r-pokedex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJCJZ-ikyWinxlOMc8nBi0BSP2CA63Mdc',
    appId: '1:838810558965:ios:bd602cae8600ea74bb80bc',
    messagingSenderId: '838810558965',
    projectId: 'butt3r-pokedex',
    storageBucket: 'butt3r-pokedex.appspot.com',
    iosClientId:
        '838810558965-fvquibescsann1vbp1bpdnr90skl29nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedex',
  );
}
